<a href="https://colab.research.google.com/github/Narc2022/-Learn-Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/Section_6_46_NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Array

* fixed type 
* Efficient
* Less flexible as compared to lists

Use np.array() to create arrays


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1);

[1 2 3 4 5]


#Fixed-type

* Numpy arrays have fixed-type
* Upcasting(Convert integer to floats)

In [ ]:
import numpy as np

arr1 = np.array([3.14,2,5,6,7])
print(arr1);

[3.14 2.   5.   6.   7.  ]


In [ ]:
import numpy as np

arr1 = np.array([1,2,5,6,7],dtype='float32')
print(arr1);

[1. 2. 5. 6. 7.]


#2D ARRAY IN NUMPY

* TWO D ARRAY ARE LOOK LIKE MATRIX

In [ ]:
import numpy as np

arr2D = np.array([[2,3,5,7,8],[1,2,5,6,7],[2,3,5,7,8]],dtype='float')
print(arr2D);
print('----------------------');
arr2d = np.array([[1,2,5,6,7],[2,3,5,7,8]],dtype='int')
print(arr2d);

[[2. 3. 5. 7. 8.]
 [1. 2. 5. 6. 7.]
 [2. 3. 5. 7. 8.]]
----------------------
[[1 2 5 6 7]
 [2 3 5 7 8]]


#Way to initialize array

np.zeros()
need to deal computer image,pad images like stuffs


In [ ]:
np.zeros(10,dtype=int)



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The np.ones() function returns a new array of given shape and type, with ones.

In [ ]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.random.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [ ]:
np.random.random((3*3))

array([0.58299588, 0.70465507, 0.27068416, 0.42690867, 0.82087082,
       0.20459618, 0.36502046, 0.87557539, 0.56114407])

In [ ]:
#practice
np.random.random((3*3))*2

array([1.18004649, 0.10946453, 0.54300614, 0.10349054, 0.65510084,
       0.35365089, 1.0249005 , 1.56709044, 0.06120239])